# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: google/cloud-sdk:218.0.0

    environment:
      - PYTHONPATH: /usr/local/google_appengine

    steps:
      - run:
          name: Check Python version
          command: |
            export VER_REGEX="^Python 2\.7(\.[0-9]+)?$"
            export PY_VER=$(python --version 2>&1)
            if ! [[ "$PY_VER" =~ $VER_REGEX ]] ; then echo "$PY_VER is not the expected version" && exit 1 ; fi

      - checkout

      - run:
          name: Install virtualenv
          command: pip install virtualenv

      - run:
          name: Activate virtualenv on project
          command: |
            python -m virtualenv -p python virtualenv
            . virtualenv/bin/activate

      - run:
          name: Install project dependencies and set PYTHONPATH
          command: |
            pip install -t lib -r requirements.txt --ignore-installed
            export PYTHONPATH=$(pwd)/lib

      - run:
          name: Run tests
          command: |
            echo "Using Python: $(which python)"
            env | sort
            python -c "import sys; print '\n'.join(sys.path)"
            python tests/test_runner.py `gcloud info --format="value(installation.sdk_root)"`

  tag:
    docker:
      - image: alpine/git

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ab:2d:12:de:d1:ac:36:0b:6a:02:92:3f:2c:49:98:c9"
      - checkout
      - run:
          when: on_success
          command: |
            echo 'export TAG_NAME=dev_tests_passed_$(date +%s)' >> $BASH_ENV
            source $BASH_ENV
            git tag $TAG_NAME
            git push origin $TAG_NAME

workflows:
  version: 2
  test-and-tag:
    jobs:
      - test
      - tag:
          requires:
            - test
          filters:
            branches:
              only: develop
