# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      # NOTE! When updating the version here, you must ensure that the image has python 2.7
      - image: google/cloud-sdk:218.0.0

    environment:
      - PYTHONPATH: /usr/local/google_appengine

    steps:
      - checkout

      - run: pip install virtualenv

      - run:
          name: enable virtualenv on project
          command: |
            python2.7 -m virtualenv virtualenv
            . virtualenv/bin/activate

      - run:
          name: pip install project dependencies
          command: pip install -t lib/ -r requirements.txt

      - run:
          name: run tests
          command: python tests/test_runner.py `gcloud info --format="value(installation.sdk_root)"`

  tag:
    docker:
      - image: alpine/git

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ab:2d:12:de:d1:ac:36:0b:6a:02:92:3f:2c:49:98:c9"
      - checkout
      - run:
          when: on_success
          command: |
            echo 'export TAG_NAME=dev_tests_passed_$(date +%s)' >> $BASH_ENV
            source $BASH_ENV
            git tag $TAG_NAME
            git push origin $TAG_NAME

workflows:
  version: 2
  test-and-tag:
    jobs:
      - test
      - tag:
          requires:
            - test
          filters:
            branches:
              only: develop
