# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  docker-build:
    machine: true
    steps:
      - checkout
      - run: docker build -t databiosphere/bond:build-$CIRCLE_BANCH -f docker/Dockerfile .

  test:
    docker:
      - image: databiosphere/bond:build-$CIRCLE_BANCH

    environment:
      - PYTHONPATH: /usr/local/google_appengine

    steps:
      - checkout

      - run:
          name: Install virtualenv
          command: pip install virtualenv

      - run:
          name: Activate virtualenv on project
          command: |
            python2.7 -m virtualenv virtualenv
            . virtualenv/bin/activate

      - run:
          name: Install project dependencies
          command: pip install -t lib/ -r requirements.txt

      - run:
          name: Run tests
          command: python tests/test_runner.py `gcloud info --format="value(installation.sdk_root)"`

  tag:
    docker:
      - image: alpine/git

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ab:2d:12:de:d1:ac:36:0b:6a:02:92:3f:2c:49:98:c9"
      - checkout
      - run:
          when: on_success
          command: |
            echo 'export TAG_NAME=dev_tests_passed_$(date +%s)' >> $BASH_ENV
            source $BASH_ENV
            git tag $TAG_NAME
            git push origin $TAG_NAME

workflows:
  version: 2
  test-and-tag:
    jobs:
      - docker-build
      - test:
          requires:
            - docker-build
      - tag:
          requires:
            - test
          filters:
            branches:
              only: develop
