version: '2'
services:
  bond-app:
    # Image id from local docker build or remote image like 'us-central1-docker.pkg.dev/dsp-artifact-registry/bond/bond:{tag}'
    image: $IMAGE_ID
    volumes:
      # Use locally rendered config.ini file.
      - $PWD/config.ini:/app/config.ini
    ports:
      - "8080:8080"
    environment:
      DATASTORE_EMULATOR_HOST: datastore-emulator:8432
  datastore-emulator:
    image: google/cloud-sdk:276.0.0
    # Use local run_emulator.sh.
    volumes:
      - $PWD/tests/datastore_emulator/run_emulator.sh:/run_emulator.sh
    command: /run_emulator.sh
