name: dsp-appsec-trivy
on: [pull_request]

jobs:
  appsec-trivy:
    # Parse Dockerfile and build, scan image if a "blessed" base image is not used
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Change the working directory to the "docker" folder
      - name: Change to docker directory
        run: cd docker
      - uses: broadinstitute/dsp-appsec-trivy-action@v1